name: Release Build

on:
  release:
    types: [published]

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Azure Function artifact
        run: |
          mkdir -p azure_function_release
          cp *.py azure_function_release/
          cp requirements.txt azure_function_release/
          cp host.json azure_function_release/

      # Download file from https://github.com/Geovation/catalyst-ons-geographies/releases/latest/download/ons_postcodes.duckdb
      - name: Download ONS Postcodes file
        run: |
          mkdir -p azure_function_release/data
          curl "https://github.com/Geovation/catalyst-ons-geographies/releases/latest/download/ons_postcodes.duckdb" -L -o ons_postcodes.duckdb
          mv ons_postcodes.duckdb azure_function_release/data/

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: azure-function-release
          path: azure_function_release/